language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - ln -s .. node_modules/karma-closure

script:
  - grunt travis
  - karma start test-app/karma.conf.js --browsers Firefox --single-run
